### PR TITLE
#Issue 8 : Added SignUp Animation

### PR DESCRIPTION
**Pull request by Harshit-3905**
Closes # Issue 8 :Add SignUp Animation

Describe the changes you've made
Added SignUp Animation to the SignUp Button 

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ]  Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

Checklist:
 
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x]  I have commented my code, particularly wherever it was hard to understand.
- [x]  I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.
 
Screenshots
image
ON Hovering over the button 
image

### CODE REVIEW

**Comment by soujo** [comment]
> Added SignUp Animation

Follow the PR template , Make the necessary changes

**Comment by Harshit-3905** [comment]
@soujo Please Review it.

**Comment by soujo** [comment]
> @soujo Please Review it.

I don't think the red colour would look good, you may use gray or any other light color

**Comment by Harshit-3905** [comment]
image
What about this colour?

**Comment by soujo** [comment]
> image What about this colour?

How about only change the color of the arrow box when we hover

**Pull request closed without merging**
