### PR TITLE
Logo created

### LINKED ISSUE #10: Codeaon : Design a logo
## Task 
- Design the logo for the website 
- Take reference from the internet 
- Don't make it too fancy

### PR DESCRIPTION
**Pull request by srini047**
## Linked Issue 

Closes: #10

### Describe the changes you've made

Made the logo for codeaon website and added the logo in the respective folder.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

codeaon-logo

### CODE REVIEW

**Comment by soujo** [comment]
@srini047 
This logo includes the name with the tagline, but we don't want that 
We just need a logo for the navbar and favicon 
Make the logo according to that

**Comment by srini047** [comment]
> @srini047 This logo includes the name with the tagline, but we don't want that We just need a logo for the navbar and favicon Make the logo according to that

Sure will do the needful.

**Comment by srini047** [comment]
codeaon-logo
Here's the refurbished logo.

**Review by soujo — APPROVED** [review]
Good work !

**Pull request merged**
